name: shellcheck2
on:
  pull_request:
    branches: 
      - master
jobs:
  shellcheck_from_CICDToolbox:
    runs-on: ubuntu-latest
    steps:
    - name: Run Shellcheck
      run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
